version: 0.2

phases:
  build:
    commands:
      - SRC_GITHUB_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF} | cut -d "/" -f3-)
      - DEST_GITHUB_BRANCH=$(echo ${CODEBUILD_WEBHOOK_BASE_REF} | cut -d "/" -f3-)
      - GIT_COMMIT_SHA=$(git rev-parse $DEST_GITHUB_BRANCH)
      - GIT_COMMIT_SHORT_SHA=$(git rev-parse --short=8 $DEST_GITHUB_BRANCH)
      - RELEASE_DATE=$(date +'%Y%m%d')
      - RELEASE_VER=$(cat VERSION)

      - |
        cat << EOF > agent.json
        {
          "agentReleaseVersion" : "$RELEASE_VER",
          "releaseDate" : "$RELEASE_DATE",
          "initStagingConfig": {
            "release": "1"
          },
          "agentStagingConfig": {
            "releaseGitSha": "$GIT_COMMIT_SHA",
            "releaseGitShortSha": "$GIT_COMMIT_SHORT_SHA",
            "gitFarmRepoName": "MadisonContainerAgentExternal",
            "gitHubRepoName": "aws/amazon-ecs-agent",
            "gitFarmStageBranch": "v${RELEASE_VER}-stage",
            "githubReleaseUrl": ""
          }
        }
        EOF

      # Downloading the agentVersionV2-<branch>.json (it is assumed that it already exists)
      - aws s3 cp ${RESULTS_BUCKET_URI}/agentVersionV2/agentVersionV2-${SRC_GITHUB_BRANCH}.json ./agentVersionV2-${SRC_GITHUB_BRANCH}.json
      # Grabbing the new current and release agent version
      - CURR_VER=$(jq -r '.releaseAgentVersion' agentVersionV2-${SRC_GITHUB_BRANCH}.json)
      # Outputting updated agentVersion-<branch>.json file
      - cat <<< $(jq '.releaseAgentVersion = '\"$RELEASE_VER\"' | .currentAgentVersion = '\"$CURR_VER\"'' agentVersionV2-${SRC_GITHUB_BRANCH}.json) > agentVersionV2-${SRC_GITHUB_BRANCH}-COPY.json
      # Formatting file by copying over temp file
      - jq . agentVersionV2-${SRC_GITHUB_BRANCH}-COPY.json > agentVersionV2-${SRC_GITHUB_BRANCH}.json

      # Uploading new agentVersionV2-<branch>.json and agent.json files
      - aws s3 cp ./agentVersionV2-${SRC_GITHUB_BRANCH}.json ${RESULTS_BUCKET_URI}/agentVersionV2/agentVersionV2-${SRC_GITHUB_BRANCH}.json
      - aws s3 cp ./agent.json ${RESULTS_BUCKET_URI}/${SRC_GITHUB_BRANCH}/agent.json