#!/bin/bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

CUR_DIR=$(pwd)

docker run \
	-v ${CUR_DIR}:/out \
	-v ${CUR_DIR}/appmesh-plugin-validator.go:/in/appmesh-plugin-validator.go \
	-v ${CUR_DIR}/go.mod:/in/go.mod\
	-v ${CUR_DIR}/go.sum:/in/go.sum \
	-e CGO_ENABLED=0 \
	-e GO111MODULE=on \
	-w /in \
	golang:1.12 go build -a -x -ldflags '-s' -o /out/appmesh-plugin-validator /in/appmesh-plugin-validator.go
