// Code generated by smithy-go-codegen DO NOT EDIT.


package types

import (
	smithydocument "github.com/aws/smithy-go/document"
)

type ASMAuthData struct {
	
	CredentialsParameter *string
	
	Region *string
	
	noSmithyDocumentSerde
}

type Association struct {
	
	Containers []string
	
	Content *EncodedString
	
	Name *string
	
	Type AssociationType
	
	noSmithyDocumentSerde
}

type Attachment struct {
	
	AttachmentArn *string
	
	AttachmentProperties []AttachmentProperty
	
	AttachmentType *string
	
	noSmithyDocumentSerde
}

type AttachmentProperty struct {
	
	Name *string
	
	Value *string
	
	noSmithyDocumentSerde
}

type Container struct {
	
	Command []string
	
	ContainerArn *string
	
	Cpu *int32
	
	CredentialSpecs []string
	
	DependsOn []ContainerDependency
	
	DockerConfig *DockerConfig
	
	EntryPoint []string
	
	Environment map[string]string
	
	EnvironmentFiles []EnvironmentFile
	
	Essential *bool
	
	FirelensConfiguration *FirelensConfiguration
	
	HealthCheckType HealthCheckType
	
	Image *string
	
	Links []string
	
	LogsAuthStrategy AuthStrategy
	
	ManagedAgents []ManagedAgent
	
	Memory *int32
	
	MountPoints []MountPoint
	
	Name *string
	
	NetworkInterfaceNames []string
	
	Overrides *string
	
	PortMappings []PortMapping
	
	RegistryAuthentication *RegistryAuthenticationData
	
	RestartPolicy *RestartPolicy
	
	Secrets []Secret
	
	StartTimeout *int32
	
	StopTimeout *int32
	
	VolumesFrom []VolumeFrom
	
	noSmithyDocumentSerde
}

type ContainerDependency struct {
	
	Condition ContainerCondition
	
	ContainerName *string
	
	noSmithyDocumentSerde
}

type DockerConfig struct {
	
	Config *string
	
	HostConfig *string
	
	Version *string
	
	noSmithyDocumentSerde
}

type DockerVolumeConfiguration struct {
	
	Autoprovision *bool
	
	Driver *string
	
	DriverOpts map[string]string
	
	Labels map[string]string
	
	Scope Scope
	
	noSmithyDocumentSerde
}

type EBSVolumeConfiguration struct {
	
	DeleteOnTermination *bool
	
	DeviceName *string
	
	FilesystemType *string
	
	VolumeId *string
	
	noSmithyDocumentSerde
}

type ECRAuthData struct {
	
	EndpointOverride *string
	
	Region *string
	
	RegistryId *string
	
	UseExecutionRole *bool
	
	noSmithyDocumentSerde
}

type EFSAuthorizationConfig struct {
	
	AccessPointId *string
	
	Iam EFSAuthorizationConfigIAM
	
	noSmithyDocumentSerde
}

type EFSVolumeConfiguration struct {
	
	AuthorizationConfig *EFSAuthorizationConfig
	
	FileSystemId *string
	
	RootDirectory *string
	
	TransitEncryption EFSTransitEncryption
	
	TransitEncryptionPort *int32
	
	noSmithyDocumentSerde
}

type ElasticNetworkInterface struct {
	
	AttachmentArn *string
	
	DomainName []string
	
	DomainNameServers []string
	
	Ec2Id *string
	
	Index *int32
	
	InterfaceAssociationProtocol NetworkInterfaceAssociationProtocol
	
	InterfaceTunnelProperties *NetworkInterfaceTunnelProperties
	
	InterfaceVethProperties *NetworkInterfaceVethProperties
	
	InterfaceVlanProperties *NetworkInterfaceVlanProperties
	
	Ipv4Addresses []IPv4AddressAssignment
	
	Ipv6Addresses []IPv6AddressAssignment
	
	MacAddress *string
	
	Name *string
	
	PrivateDnsName *string
	
	SubnetGatewayIpv4Address *string
	
	noSmithyDocumentSerde
}

type EncodedString struct {
	
	Encoding Encoding
	
	Value *string
	
	noSmithyDocumentSerde
}

type EnvironmentFile struct {
	
	Type EnvironmentFileType
	
	Value *string
	
	noSmithyDocumentSerde
}

type FirelensConfiguration struct {
	
	Options map[string]string
	
	Type FirelensConfigurationType
	
	noSmithyDocumentSerde
}

type FSxWindowsFileServerAuthorizationConfig struct {
	
	CredentialsParameter *string
	
	Domain *string
	
	noSmithyDocumentSerde
}

type FSxWindowsFileServerVolumeConfiguration struct {
	
	AuthorizationConfig *FSxWindowsFileServerAuthorizationConfig
	
	FileSystemId *string
	
	RootDirectory *string
	
	noSmithyDocumentSerde
}

type HostVolumeProperties struct {
	
	SourcePath *string
	
	noSmithyDocumentSerde
}

type IAMRoleCredentials struct {
	
	AccessKeyId *string
	
	CredentialScope *string
	
	CredentialsId *string
	
	Expiration *string
	
	RoleArn *string
	
	SecretAccessKey *string
	
	SessionToken *string
	
	noSmithyDocumentSerde
}

type IPv4AddressAssignment struct {
	
	Primary *bool
	
	PrivateAddress *string
	
	noSmithyDocumentSerde
}

type IPv6AddressAssignment struct {
	
	Address *string
	
	noSmithyDocumentSerde
}

type ManagedAgent struct {
	
	Name ManagedAgentName
	
	Properties map[string]string
	
	noSmithyDocumentSerde
}

type MountPoint struct {
	
	ContainerPath *string
	
	ReadOnly *bool
	
	SourceVolume *string
	
	noSmithyDocumentSerde
}

type NetworkInterfaceTunnelProperties struct {
	
	InterfaceIpAddress *string
	
	TunnelId *string
	
	noSmithyDocumentSerde
}

type NetworkInterfaceVethProperties struct {
	
	PeerInterface *string
	
	noSmithyDocumentSerde
}

type NetworkInterfaceVlanProperties struct {
	
	TrunkInterfaceMacAddress *string
	
	VlanId *string
	
	noSmithyDocumentSerde
}

type PortMapping struct {
	
	ContainerPort *int32
	
	ContainerPortRange *string
	
	HostPort *int32
	
	Protocol TransportProtocol
	
	noSmithyDocumentSerde
}

type ProxyConfiguration struct {
	
	ContainerName *string
	
	Properties map[string]string
	
	Type ProxyConfigurationType
	
	noSmithyDocumentSerde
}

type RegistryAuthenticationData struct {
	
	AsmAuthData *ASMAuthData
	
	EcrAuthData *ECRAuthData
	
	Type AuthenticationType
	
	noSmithyDocumentSerde
}

type RestartPolicy struct {
	
	// This member is required.
	Enabled *bool
	
	IgnoredExitCodes []int32
	
	RestartAttemptPeriod *int32
	
	noSmithyDocumentSerde
}

type Secret struct {
	
	ContainerPath *string
	
	Name *string
	
	Provider SecretProvider
	
	Region *string
	
	Target SecretTarget
	
	Type SecretType
	
	ValueFrom *string
	
	noSmithyDocumentSerde
}

type Task struct {
	
	AgentConfiguration *string
	
	Arn *string
	
	Associations []Association
	
	Attachments []Attachment
	
	Containers []Container
	
	Cpu *float64
	
	DesiredStatus *string
	
	ElasticNetworkInterfaces []ElasticNetworkInterface
	
	EnableFaultInjection *bool
	
	ExecutionRoleCredentials *IAMRoleCredentials
	
	Family *string
	
	IpcMode *string
	
	LaunchType *string
	
	Memory *int32
	
	NetworkMode *string
	
	Overrides *string
	
	PidMode *string
	
	ProxyConfiguration *ProxyConfiguration
	
	RoleCredentials *IAMRoleCredentials
	
	ServiceName *string
	
	TaskClusterArn *string
	
	TaskDefinitionAccountId *string
	
	Version *string
	
	Volumes []Volume
	
	Zone *string
	
	noSmithyDocumentSerde
}

type TaskIdentifier struct {
	
	DesiredStatus *string
	
	TaskArn *string
	
	TaskClusterArn *string
	
	noSmithyDocumentSerde
}

type UpdateInfo struct {
	
	Location *string
	
	Signature *string
	
	noSmithyDocumentSerde
}

type VersionInfo struct {
	
	AgentHash *string
	
	AgentVersion *string
	
	DockerVersion *string
	
	noSmithyDocumentSerde
}

type Volume struct {
	
	DockerVolumeConfiguration *DockerVolumeConfiguration
	
	EbsVolumeConfiguration *EBSVolumeConfiguration
	
	EfsVolumeConfiguration *EFSVolumeConfiguration
	
	FsxWindowsFileServerVolumeConfiguration *FSxWindowsFileServerVolumeConfiguration
	
	Host *HostVolumeProperties
	
	Name *string
	
	Type VolumeType
	
	noSmithyDocumentSerde
}

type VolumeFrom struct {
	
	ReadOnly *bool
	
	SourceContainer *string
	
	noSmithyDocumentSerde
}

type noSmithyDocumentSerde = smithydocument.NoSerde
