// Code generated by smithy-go-codegen DO NOT EDIT.


package ecs

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/service/ecs/types"
)

func (c *Client) DescribeDaemonTaskDefinition(ctx context.Context, params *DescribeDaemonTaskDefinitionInput, optFns ...func(*Options)) (*DescribeDaemonTaskDefinitionOutput, error) {
	if params == nil { params = &DescribeDaemonTaskDefinitionInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "DescribeDaemonTaskDefinition", params, optFns, c.addOperationDescribeDaemonTaskDefinitionMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*DescribeDaemonTaskDefinitionOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type DescribeDaemonTaskDefinitionInput struct {
	
	// This member is required.
	DaemonTaskDefinition *string
	
	noSmithyDocumentSerde
}

type DescribeDaemonTaskDefinitionOutput struct {
	
	DaemonTaskDefinition *types.DaemonTaskDefinition
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (c *Client) addOperationDescribeDaemonTaskDefinitionMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = addOpDescribeDaemonTaskDefinitionValidationMiddleware(stack); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opDescribeDaemonTaskDefinition(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opDescribeDaemonTaskDefinition(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "DescribeDaemonTaskDefinition",
	}
}
