FROM golang:1.3

RUN mkdir /out
VOLUME ['/out']

RUN mkdir -p /go/src/github.com/aws/
RUN go get github.com/tools/godep


COPY . /go/src/github.com/aws/amazon-ecs-agent

WORKDIR /go/src/github.com/aws/amazon-ecs-agent/agent

ENTRYPOINT ../scripts/build
