# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

ARG GO_VERSION
FROM public.ecr.aws/docker/library/golang:${GO_VERSION}
MAINTAINER Amazon Web Services, Inc.

ENV XDG_CACHE_HOME /tmp

COPY ./scripts/cleanbuild /scripts/cleanbuild
WORKDIR /go/src/github.com/aws/amazon-ecs-agent

# Set subfolder permissions to 777
# https://github.com/docker-library/golang/blob/2f2f3b620d61f533484f24a568c2ca46e4fda91c/1.9/stretch/Dockerfile#L49
RUN chmod -R 777 /go/src
ENTRYPOINT /scripts/cleanbuild
