FROM golang:1.3
MAINTAINER Amazon Web Services, Inc.

RUN mkdir /out
VOLUME ['/out']

RUN mkdir -p /go/src/github.com/aws/
RUN go get github.com/tools/godep


WORKDIR /go/src/github.com/aws/amazon-ecs-agent/agent

ENTRYPOINT ../scripts/build
