# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

ARG GO_VERSION
FROM public.ecr.aws/docker/library/golang:${GO_VERSION}
MAINTAINER Amazon Web Services, Inc.

ARG GOARCH

ENV GOARCH ${GOARCH}
ENV XDG_CACHE_HOME /tmp

ENV GOFLAGS=-mod=vendor

RUN mkdir -p /go/src/github.com/aws/

WORKDIR /go/src/github.com/aws/amazon-vpc-cni-plugins

CMD ["make", "vpc-eni", "aws-appmesh", "vpc-branch-eni", "ecs-serviceconnect"]
