// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//	http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package acsclient

import (
	"github.com/aws/amazon-ecs-agent/ecs-agent/wsclient"

	ecsacs "github.com/aws/aws-sdk-go-v2/service/acs"
	acstypes "github.com/aws/aws-sdk-go-v2/service/acs/types"
)

var acsRecognizedTypes []interface{}

func init() {
	// This list is currently *manually updated* and assumes that the generated
	// struct type-names within the package *exactly match* the type sent by ACS/TCS
	// (true so far; careful with inflections)
	// TODO, this list should be autogenerated
	// I couldn't figure out how to get a list of all structs in a package via
	// reflection, but that would solve this. The alternative is to either parse
	// the .json model or the generated struct names.
	acsRecognizedTypes = []interface{}{
		ecsacs.HeartbeatInput{},
		ecsacs.HeartbeatOutput{},
		ecsacs.PayloadMessage{},
		ecsacs.PollOutput{},
		ecsacs.AckRequest{},
		ecsacs.UpdateFailureInput{},
		ecsacs.PerformUpdateInput{},
		ecsacs.StageUpdateInput{},
		ecsacs.RefreshTaskIAMRoleCredentialsInput{},
		ecsacs.RefreshTaskIAMRoleCredentialsOutput{},
		acstypes.ServerException{},
		acstypes.BadRequestException{},
		acstypes.InvalidClusterException{},
		acstypes.InvalidInstanceException{},
		acstypes.AccessDeniedException{},
		acstypes.InactiveInstanceException{},
		ecsacs.ErrorInput{},
		ecsacs.AttachTaskNetworkInterfacesInput{},
		ecsacs.AttachInstanceNetworkInterfacesInput{},
		ecsacs.ConfirmAttachmentInput{},
		ecsacs.TaskManifestMessage{},
		ecsacs.TaskStopVerificationOutput{},
		ecsacs.TaskStopVerificationInput{},
	}
}

func NewACSDecoder() wsclient.TypeDecoder {
	return wsclient.BuildTypeDecoder(acsRecognizedTypes)
}
