#!/bin/bash
# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

CUR_DIR=$(pwd)
AGENT_VENDOR_DIR=$(echo $(cd ${CUR_DIR}/../../agent/vendor;pwd))

docker run \
	-v ${CUR_DIR}:/out \
	-v ${CUR_DIR}/agent-introspection-validator.go:/in/agent-introspection-validator.go \
	-v ${AGENT_VENDOR_DIR}:/gopath/src \
	-e CGO_ENABLED=0 \
	-e GOPATH=/go:/gopath \
	golang:1.9 go build -a -x -ldflags '-s' -o /out/agent-introspection-validator /in/agent-introspection-validator.go
