name: 'Repository Setup'
description: 'Sets up the repository to run checks'
runs:
  using: "composite"
    steps:
      - name: get GO_VERSION
        id: get-go-version
        run:  |
          cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
          set -eou pipefail
          go_version=$(cat -e GO_VERSION)
          go_version=${go_version%?}
          go_version_length=${#go_version}
          go_version_re="^([0-9]+\.){1,2}([0-9]+)$"
          if ! [[ $go_version_length -le 10 && $go_version =~ $go_version_re ]] ; then
            echo "invalid GO version"
            exit 1
          fi
          echo "GO_VERSION=$go_version" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.get-go-version.outputs.GO_VERSION }}
      - uses: actions/checkout@v3
        with:
          path: src/github.com/aws/amazon-ecs-agent
