// Copyright 2015-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//
// Source: cmd.go in package iptables
// Automatically generated by MockGen. DO NOT EDIT!

package iptables

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Cmd interface
type MockCmd struct {
	ctrl     *gomock.Controller
	recorder *_MockCmdRecorder
}

// Recorder for MockCmd (not exported)
type _MockCmdRecorder struct {
	mock *MockCmd
}

func NewMockCmd(ctrl *gomock.Controller) *MockCmd {
	mock := &MockCmd{ctrl: ctrl}
	mock.recorder = &_MockCmdRecorder{mock}
	return mock
}

func (_m *MockCmd) EXPECT() *_MockCmdRecorder {
	return _m.recorder
}

func (_m *MockCmd) CombinedOutput() ([]byte, error) {
	ret := _m.ctrl.Call(_m, "CombinedOutput")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCmdRecorder) CombinedOutput() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CombinedOutput")
}

func (_m *MockCmd) Output() ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Output")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockCmdRecorder) Output() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Output")
}
