#!/bin/bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# this script builds the ecs/vpc cni plugins from the submodules
set -ex

# this script assumes we've run the get-cni-sources make target to update the cni submodules
ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )
cd "${ROOT}"

export BUILDDIR="$(mktemp -d)"
export GITPATH="${BUILDDIR}/src/github.com/aws"
export GOPATH="${BUILDDIR}"

mkdir -p "${GITPATH}"
ln -s "${ROOT}/amazon-ecs-cni-plugins" "${GITPATH}"
ln -s "${ROOT}/amazon-vpc-cni-plugins" "${GITPATH}"

cd ${GITPATH}/amazon-ecs-cni-plugins && GO111MODULE=auto make plugins
mkdir -p ${ROOT}/misc/plugins && cp -a ./bin/plugins/. ${ROOT}/misc/plugins/
make clean
cd ${GITPATH}/amazon-vpc-cni-plugins && GO111MODULE=off BUILD_FLAGS="-tags disablekubeapi" make all-binaries
cp -a ./build/linux_amd64/. ${ROOT}/misc/plugins/
make clean

rm -r "${BUILDDIR}"
