#!/bin/bash
# Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

export GOPATH=`godep path`:$GOPATH

# Statically link to ensure we can run in scratch
CGO_ENABLED=0 go build -a -installsuffix cgo -x -ldflags '-s' -o amazon-ecs-agent


buildErr=$?
if [[ $buildErr != 0 ]]; then
	echo "Agent build exited with error: $buildErr"
	exit $buildErr
fi


# Put it in the shared volume
cp amazon-ecs-agent /out/amazon-ecs-agent
