#! /bin/bash

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the
# "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and
# limitations under the License.
set -ex

export DOCKER_CLI_EXPERIMENTAL=enabled

dir=$(dirname "${BASH_SOURCE[0]}")
source "$dir/ci-ecr"
GO_VERSION=$(cat "$dir/../GO_VERSION")

REGISTRY_ALIAS="${1}"

usage() {
    cat <<EOF
Usage: ${0} REGISTRY_ALIAS

This script creates multi-arch manifest lists at public.ecr.aws/REGISTRY_ALIAS/ci/IMAGE_NAME
for the following images:

$IMAGES
EOF
}

if [ -z "$REGISTRY_ALIAS" ]; then
    echo "REGISTRY_ALIAS must be specified"
    usage
    exit 1
fi

aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

for image in $IMAGES; do
    repotag=(${image//:/ })
    repo="${repotag[0]}"
    tag="${repotag[1]}"

    repoName="ci/$repo"
    amd64URI=""
    arm64URI=""

    if aws ecr-public --region us-east-1 describe-images --repository-name "$repoName" --image-ids "imageTag=$tag-amd64"; then
        amd64URI="public.ecr.aws/$REGISTRY_ALIAS/ci/$repo:$tag-amd64"
    fi
    if aws ecr-public --region us-east-1 describe-images --repository-name "$repoName" --image-ids "imageTag=$tag-arm64"; then
        arm64URI="public.ecr.aws/$REGISTRY_ALIAS/ci/$repo:$tag-arm64"
    fi
    if ! aws ecr-public --region "us-east-1" describe-repositories --repository-names "$repoName" &>/dev/null; then
        aws ecr-public --region "us-east-1" create-repository --repository-name "$repoName"
    fi

    docker manifest create --amend "public.ecr.aws/$REGISTRY_ALIAS/$repoName:$tag" $amd64URI $arm64URI
    docker manifest push "public.ecr.aws/$REGISTRY_ALIAS/$repoName:$tag"
done
