#!/bin/bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
#
# The script is to upload linux images used by integration tests and functional
# tests to ECR

set -ex

# This script is being skipped because it is part of a deprecated codebuild
# path. Since it relies on pulling from dockerhub, it could fail our build steps
# even though it is not necessary. This script can be deleted completely when
# our github hook code is deprecated.
exit 0
