#! /bin/bash

# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the
# "License"). You may not use this file except in compliance
#  with the License. A copy of the License is located at
#
#     http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and
# limitations under the License.

AGENT_VERSION="${1:-}"
INIT_VERSION="${AGENT_VERSION}-1"
BUCKET_NAME="${2:-}"
SHA=$(git rev-parse --short=8 HEAD)

usage() {
	echo "Usage: ${0} AGENT_VERSION BUCKET_NAME"
}

if [[ $AGENT_VERSION == "" ]]; then
    usage
    exit
fi
if [[ $BUCKET_NAME == "" ]]; then
    usage
    exit
fi

files="ecs-agent-latest.tar
ecs-agent-latest.tar.md5
ecs-agent-latest.tar.json
ecs-agent-latest.tar.asc
ecs-agent-v${AGENT_VERSION}.tar
ecs-agent-v${AGENT_VERSION}.tar.md5
ecs-agent-v${AGENT_VERSION}.tar.json
ecs-agent-v${AGENT_VERSION}.tar.asc
ecs-agent-${SHA}.tar
ecs-agent-${SHA}.tar.md5
ecs-agent-${SHA}.tar.json
ecs-agent-${SHA}.tar.asc
ecs-agent-windows-latest.zip
ecs-agent-windows-latest.zip.md5
ecs-agent-windows-latest.zip.json
ecs-agent-windows-latest.zip.asc
ecs-agent-windows-v${AGENT_VERSION}.zip
ecs-agent-windows-v${AGENT_VERSION}.zip.md5
ecs-agent-windows-v${AGENT_VERSION}.zip.json
ecs-agent-windows-v${AGENT_VERSION}.zip.asc
ecs-agent-windows-${SHA}.zip
ecs-agent-windows-${SHA}.zip.md5
ecs-agent-windows-${SHA}.zip.json
ecs-agent-windows-${SHA}.zip.asc
ecs-agent-arm64-latest.tar
ecs-agent-arm64-latest.tar.md5
ecs-agent-arm64-latest.tar.json
ecs-agent-arm64-latest.tar.asc
ecs-agent-arm64-v${AGENT_VERSION}.tar
ecs-agent-arm64-v${AGENT_VERSION}.tar.md5
ecs-agent-arm64-v${AGENT_VERSION}.tar.json
ecs-agent-arm64-v${AGENT_VERSION}.tar.asc
ecs-agent-arm64-${SHA}.tar
ecs-agent-arm64-${SHA}.tar.md5
ecs-agent-arm64-${SHA}.tar.json
ecs-agent-arm64-${SHA}.tar.asc
ecs-anywhere-install-latest.sh
ecs-anywhere-install-latest.sh.asc
ecs-anywhere-install-${INIT_VERSION}.sh
ecs-anywhere-install-${INIT_VERSION}.sh.asc
amazon-ecs-init-${INIT_VERSION}.x86_64.rpm
amazon-ecs-init-${INIT_VERSION}.x86_64.rpm.asc
amazon-ecs-init-${INIT_VERSION}.aarch64.rpm
amazon-ecs-init-${INIT_VERSION}.aarch64.rpm.asc
amazon-ecs-init-${INIT_VERSION}.amd64.deb
amazon-ecs-init-${INIT_VERSION}.amd64.deb.asc
amazon-ecs-init-${INIT_VERSION}.arm64.deb
amazon-ecs-init-${INIT_VERSION}.arm64.deb.asc
ecs-init-${INIT_VERSION}.amzn2.aarch64.rpm
ecs-init-${INIT_VERSION}.amzn2.aarch64.rpm.asc
ecs-init-${INIT_VERSION}.amzn2.x86_64.rpm
ecs-init-${INIT_VERSION}.amzn2.x86_64.rpm.asc
ecs-init-${INIT_VERSION}.amzn2022.aarch64.rpm
ecs-init-${INIT_VERSION}.amzn2022.aarch64.rpm.asc
ecs-init-${INIT_VERSION}.amzn2022.x86_64.rpm
ecs-init-${INIT_VERSION}.amzn2022.x86_64.rpm.asc
ecs-init-latest.amzn2.aarch64.rpm
ecs-init-latest.amzn2.aarch64.rpm.asc
ecs-init-latest.amzn2.x86_64.rpm
ecs-init-latest.amzn2.x86_64.rpm.asc
ecs-init-latest.amzn2022.aarch64.rpm
ecs-init-latest.amzn2022.aarch64.rpm.asc
ecs-init-latest.amzn2022.x86_64.rpm
ecs-init-latest.amzn2022.x86_64.rpm.asc"

# verify the files actually exist:
for f in $files; do
    echo "Verifying file exists: s3://$BUCKET_NAME/$f"
    output=$(aws s3api head-object --bucket $BUCKET_NAME --key $f)
    if [ $? != 0 ]; then
      echo "ERROR file not found: $f"
   fi
done

# do basic size-based verification that the content of the 'latest' file matches the version and sha files:
echo "Verifying contents of s3://$BUCKET_NAME/ecs-agent-latest.tar"
latest=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-latest.tar | tail --lines=2)
version=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-v${AGENT_VERSION}.tar | tail --lines=2)
sha=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-${SHA}.tar | tail --lines=2)
if [[ "$latest" != "$version" ]]; then
    echo "ERROR verifying contents of s3://$BUCKET_NAME/ecs-agent-v${AGENT_VERSION}.tar, it is not the same as s3://$BUCKET_NAME/ecs-agent-latest.tar"
fi
if [[ "$latest" != "$sha" ]]; then
    echo "ERROR verifying contents of s3://$BUCKET_NAME/ecs-agent-${SHA}.tar, it is not the same as s3://$BUCKET_NAME/ecs-agent-latest.tar"
fi


# latest windows
echo "Verifying contents of s3://$BUCKET_NAME/ecs-agent-windows-latest.zip"
latest=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-windows-latest.zip | tail --lines=2)
version=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-windows-v${AGENT_VERSION}.zip | tail --lines=2)
sha=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-windows-${SHA}.zip | tail --lines=2)
if [[ "$latest" != "$version" ]]; then
    echo "ERROR verifying contents of s3://$BUCKET_NAME/ecs-agent-windows-v${AGENT_VERSION}.zip, it is not the same as s3://$BUCKET_NAME/ecs-agent-latest.zip"
fi
if [[ "$latest" != "$sha" ]]; then
    echo "ERROR verifying contents of s3://$BUCKET_NAME/ecs-agent-windows-${SHA}.zip, it is not the same as s3://$BUCKET_NAME/ecs-agent-windows-latest.zip"
fi


# latest ARM
echo "Verifying contents of s3://$BUCKET_NAME/ecs-agent-arm64-latest.tar"
latest=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-arm64-latest.tar | tail --lines=2)
version=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-arm64-v${AGENT_VERSION}.tar | tail --lines=2)
sha=$(aws s3 ls --summarize s3://$BUCKET_NAME/ecs-agent-arm64-${SHA}.tar | tail --lines=2)
if [[ "$latest" != "$version" ]]; then
    echo "ERROR verifying contents of s3://$BUCKET_NAME/ecs-agent-arm64-v${AGENT_VERSION}.tar, it is not the same as s3://$BUCKET_NAME/ecs-agent-arm64-latest.tar"
fi
if [[ "$latest" != "$sha" ]]; then
    echo "ERROR verifying contents of s3://$BUCKET_NAME/ecs-agent-arm64-${SHA}.tar, it is not the same as s3://$BUCKET_NAME/ecs-agent-arm64-latest.tar"
fi
