// Code generated by smithy-go-codegen DO NOT EDIT.


package acs

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/service/acs/types"
)

// AttachInstanceNetworkInterfaces requests that the Agent look for and confirm
// the attachment of a network interface by the control plane that is not bound to
// a specific task.
func (c *Client) AttachInstanceNetworkInterfaces(ctx context.Context, params *AttachInstanceNetworkInterfacesInput, optFns ...func(*Options)) (*AttachInstanceNetworkInterfacesOutput, error) {
	if params == nil { params = &AttachInstanceNetworkInterfacesInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "AttachInstanceNetworkInterfaces", params, optFns, c.addOperationAttachInstanceNetworkInterfacesMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*AttachInstanceNetworkInterfacesOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type AttachInstanceNetworkInterfacesInput struct {
	
	ClusterArn *string
	
	ContainerInstanceArn *string
	
	ElasticNetworkInterfaces []types.ElasticNetworkInterface
	
	GeneratedAt *int64
	
	MessageId *string
	
	WaitTimeoutMs *int64
	
	noSmithyDocumentSerde
}

type AttachInstanceNetworkInterfacesOutput struct {
	
	Cluster *string
	
	ContainerInstance *string
	
	MessageId *string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (c *Client) addOperationAttachInstanceNetworkInterfacesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	err = stack.Serialize.Add(&awsAwsjson11_serializeOpAttachInstanceNetworkInterfaces{}, middleware.After)
	if err != nil { return err }
	err = stack.Deserialize.Add(&awsAwsjson11_deserializeOpAttachInstanceNetworkInterfaces{}, middleware.After)
	if err != nil { return err }
	if err := addProtocolFinalizerMiddlewares(stack, options, "AttachInstanceNetworkInterfaces"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opAttachInstanceNetworkInterfaces(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addSpanInitializeStart(stack); err != nil {
	return err
	}
	if err = addSpanInitializeEnd(stack); err != nil {
	return err
	}
	if err = addSpanBuildRequestStart(stack); err != nil {
	return err
	}
	if err = addSpanBuildRequestEnd(stack); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opAttachInstanceNetworkInterfaces(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "AttachInstanceNetworkInterfaces",
	}
}
