AWSTemplateFormatVersion: 2010-09-09
Description: A template that brings up a code build project that makes release configs for AL versions in maintenance mode

Parameters:
    GithubFullRepoName:
      Type: String
      Description: Full name of the agent repository to use (e.g. https://github.com/aws/amazon-ecs-agent.git)
    GithubBranchName:
      Type: String
      Description: Name of the base branch to use to build, PRs to which will trigger builds (e.g. refs/heads/dev)
    ServiceRoleArn:
      Type: String
      Description: The ARN of an existing CodeBuild service role

Resources:
  ModifyAndCopyJSON:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      BadgeEnabled: false
      ConcurrentBuildLimit: 10
      Description: A CodeBuild project to modify and update the release configs for AL versions in maintenance mode. Builds are triggered by PR merges.
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Name: !Ref 'AWS::StackName'
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Ref ServiceRoleArn
      Source:
        BuildSpec: buildspecs/al-maintenance-release-config.yml
        Location: !Ref GithubFullRepoName
        Type: GITHUB
      TimeoutInMinutes: 60
      Triggers:
        BuildType: BUILD
        FilterGroups:
          - - Type: EVENT
              Pattern: 'PULL_REQUEST_MERGED'
            - Type: BASE_REF
              Pattern: !Sub '^${GithubBranchName}$'
        Webhook: true
      Visibility: PRIVATE