---
AWSTemplateFormatVersion: "2010-09-09"
Description: A template that brings up a code pipeline that builds and signs artifacts

Parameters:
  BuildAndSignCodePipelineName:
    Type: String
    Description: The name of the code pipeline
    Default: artifact-build-sign-pipeline
  BuildCodeBuildProjectName:
    Type: String
    Description: The name of the build project
    Default: artifact-build
  SigningCodeBuildProjectName:
    Type: String
    Description: The name of the signing project
    Default: artifact-sign
  CopyCodeBuildProjectName:
    Type: String
    Description: The name of the copy project
    Default: artifact-copy
  CodeBuildLogGroupName:
    Type: String
    Description: The name of the log group to push build logs to
    Default: build-and-sign-logs
  LogGroupRetentionPeriodInDays:
    Type: Number
    Description: The number of days to retain cloudwatch logs
    Default: 180
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
  ReleaseArtifactsBucketArn:
    Type: String
    Description: The ARN of the bucket where things land at the end, this is assumed to already exist
  ReleaseArtifactsBucketS3Uri:
    Type: String
    Description: The URI of the bucket where things land at the end, this is assumed to already exist
  CodeStarConnectionArn:
    Type: String
    Description: The ARN of the connection to use to connect to GitHub
  GithubFullRepoName:
    Type: String
    Description: The name of the repository that we want to use
  GithubBranchName:
    Type: String
    Description: The name of the branch to use to build
  SecretKeyArn:
    Type: String
    Description: The ARN of the secret key
  PassphraseArn:
    Type: String
    Description: The ARN of the passphrase

Resources:
  CodeBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref CodeBuildLogGroupName
      RetentionInDays: !Ref LogGroupRetentionPeriodInDays

  BuildAndSignCodePipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}-artifacts"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BuildCodeBuildProjectServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "build-codebuild-project-service-role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: codebuild-build-base-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Resource:
                  - !GetAtt CodeBuildLogGroup.Arn
                  - !Sub "${CodeBuildLogGroup.Arn}:*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Sid: ArtifactBucketAccess
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Sid: CodeBuildCodeStarConnectionAccess
                Effect: Allow
                Resource:
                  - !Ref CodeStarConnectionArn
                Action:
                  - codestar-connections:UseConnection
              - Sid: CodeBuildCreateReportAccess
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${BuildCodeBuildProjectName}-*"
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages

  BuildCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      ConcurrentBuildLimit: 10
      Description: A sample agent build on pr
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CodeBuildLogGroupName
          Status: ENABLED
          StreamName: build
      Name: !Ref BuildCodeBuildProjectName
      QueuedTimeoutInMinutes: 60
      ServiceRole: !Ref BuildCodeBuildProjectServiceRole
      Source:
        BuildSpec: buildspecs/build.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60

  SigningCodeBuildProjectServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "signing-codebuild-project-service-role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: codebuild-signing-base-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Resource:
                  - !GetAtt CodeBuildLogGroup.Arn
                  - !Sub "${CodeBuildLogGroup.Arn}:*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Sid: ArtifactBucketAccess
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Sid: CodeBuildCreateReportAccess
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${SigningCodeBuildProjectName}-*"
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
        - PolicyName: codebuild-secretsmanager-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: SecretsManagerAccess
                Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref SecretKeyArn
                  - !Ref PassphraseArn

  SigningCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref SigningCodeBuildProjectName
      Description: A CodeBuild project that signs given artifacts
      ConcurrentBuildLimit: 10
      ServiceRole: !GetAtt SigningCodeBuildProjectServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: PASSPHRASE
            Type: SECRETS_MANAGER
            Value: !Ref PassphraseArn
          - Name: PRIVATE_KEY_ARN
            Type: PLAINTEXT
            Value: !Ref SecretKeyArn
      Source:
        BuildSpec: buildspecs/signing.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CodeBuildLogGroupName
          Status: ENABLED
          StreamName: signing

  CopyCodeBuildProjectServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "copy-codebuild-project-service-role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: codebuild-copy-base-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CloudWatchLogsAccess
                Effect: Allow
                Resource:
                  - !GetAtt CodeBuildLogGroup.Arn
                  - !Sub "${CodeBuildLogGroup.Arn}:*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Sid: ArtifactBucketAccess
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Sid: ResultsBucketAccess
                Effect: Allow
                Resource:
                  - !Ref ReleaseArtifactsBucketArn
                  - !Sub "${ReleaseArtifactsBucketArn}/*"
                Action: s3:*
              - Sid: CodeBuildCreateReportAccess
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${CopyCodeBuildProjectName}-*"
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages

  CopyCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CopyCodeBuildProjectName
      Description: A CodeBuild project that copies given artifacts
      ConcurrentBuildLimit: 10
      ServiceRole: !GetAtt CopyCodeBuildProjectServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        ImagePullCredentialsType: CODEBUILD
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        EnvironmentVariables:
          - Name: RESULTS_BUCKET_URI
            Type: PLAINTEXT
            Value: !Ref ReleaseArtifactsBucketS3Uri
      Source:
        BuildSpec: buildspecs/copy.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref CodeBuildLogGroupName
          Status: ENABLED
          StreamName: copy

  BuildAndSignCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "build-and-sign-codepipeline-service-role-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: build-and-sign-codepipeline-base-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: CodePipelinePassRoleAccess
                Effect: Allow
                Resource: "*"
                Action:
                  - iam:PassRole
                Condition:
                  StringEqualsIfExists:
                    iam:PassedToService:
                      - cloudformation.amazonaws.com
                      - elasticbeanstalk.amazonaws.com
                      - ec2.amazonaws.com
                      - ecs-tasks.amazonaws.com
              - Sid: CodePipelineGithubConnectionsAccess
                Effect: Allow
                Resource: "*"
                Action:
                  - codestar-connections:UseConnection
              - Sid: CodePipelineReadAndWriteToS3Access
                Effect: Allow
                Resource: "*"
                Action:
                  - s3:*
              - Sid: CodePipelineCodeBuildAccess
                Effect: Allow
                Resource: "*"
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuildBatches
                  - codebuild:StartBuildBatch

  BuildAndSignCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref BuildAndSignCodePipelineName
      RoleArn: !GetAtt BuildAndSignCodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}-artifacts"
      Stages:
        - Name: Source
          Actions:
            - Name: Github
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: "1"
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref GithubFullRepoName
                BranchName: !Ref GithubBranchName
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
              Namespace: SourceVariables
        - Name: Build
          Actions:
            - Name: Make
              InputArtifacts:
                - Name: SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildCodeBuildProject
                EnvironmentVariables: '[{"name":"GIT_COMMIT_SHA","value":"#{SourceVariables.CommitId}","type":"PLAINTEXT"}]'
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        - Name: Sign
          Actions:
            - Name: GPG
              InputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref SigningCodeBuildProject
                EnvironmentVariables: '[{"name":"GIT_COMMIT_SHA","value":"#{SourceVariables.CommitId}","type":"PLAINTEXT"}]'
              OutputArtifacts:
                - Name: SignedArtifact
              RunOrder: 1
        - Name: Copy
          Actions:
            - Name: ToS3
              InputArtifacts:
                - Name: SignedArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CopyCodeBuildProject
                EnvironmentVariables: '[{"name":"GIT_COMMIT_SHA","value":"#{SourceVariables.CommitId}","type":"PLAINTEXT"}]'
              RunOrder: 1
