#!/bin/bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
#	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

GO_VERSION=$(cat ../../GO_VERSION)

if ! docker images | awk '{print $1":"$2}' | grep "amazon/amazon-ecs-exec-command-agent-test:make" > /dev/null ; then
	docker build --build-arg GO_VERSION=$GO_VERSION -t "amazon/amazon-ecs-exec-command-agent-test:make" -f "linux.dockerfile" .
fi
